### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera It works now! :)

**Comment by nguerrera** [comment]
Excellent

**Comment by tmat** [comment]
@nguerrera Could you please send a pointer to this repo to the loc team, so they can translate?

**Comment by nguerrera** [comment]
@tmat Yes. Do any of these localized bits ship inside Visual Studio? I need to communicate the priority accordingly.

**Comment by tmat** [comment]
@nguerrera Not shipping in VS. Lower pri than VS for sure.

**Pull request merged**
